version: '3.5'
services:
    rabbitmq:
        hostname: rabbit
        container_name: rabbitmq
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
        networks:
            - my_network
    database:
        hostname: mongo
        container_name: database
        image: mongo:latest
        ports:
            - "27018:27017"
        networks:
            - my_network
            
networks:
    my_network:
        driver: bridge
