version: '3.5'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"
        networks:
            - my_network

    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
        networks:
            - my_network
    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27017"
        networks:
            - my_network

    pgi-import-flower:
        image: mher/flower
        container_name: pgi-import-flower
        ports:
            - "5556:5555"
        networks:
            - my_network

networks:
    my_network:
        name: my_network
